### ISSUE TITLE
method onPressed is not synchronize with the animation

### ISSUE THREAD

**Issue by wH1t3-l0tUs** [fatihozkan-github/ExpandableWidgets#1]
Users can perform click even when the animation is in progress, it should perform right after the animation starts and before the animation finishes, the user can not perform click again

**Comment by fatihozkan-github** [comment]
Hi Trung,
Thanks for opening this issue. 
I'm planning to push a new version for ExpandableWidgets and address some bugs & issues. I will try to close this issue with the new version. Sorry for being late, I have been very busy lately.
Best regards,
Fatih
